/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CreateEditProduct`; params?: Router.UnknownInputParams; } | { pathname: `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/MainPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProductAdd`; params?: Router.UnknownInputParams; } | { pathname: `/ProductPage`; params?: Router.UnknownInputParams; } | { pathname: `/ShopHeader`; params?: Router.UnknownInputParams; } | { pathname: `/ShopPage`; params?: Router.UnknownInputParams; } | { pathname: `/ShopProducts`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/api/controllers/new-controller`; params?: Router.UnknownInputParams; } | { pathname: `/router/Router`; params?: Router.UnknownInputParams; } | { pathname: `/types/common/data.types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CreateEditProduct`; params?: Router.UnknownOutputParams; } | { pathname: `/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/MainPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductAdd`; params?: Router.UnknownOutputParams; } | { pathname: `/ProductPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ShopHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/ShopPage`; params?: Router.UnknownOutputParams; } | { pathname: `/ShopProducts`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/api`; params?: Router.UnknownOutputParams; } | { pathname: `/api/controllers/new-controller`; params?: Router.UnknownOutputParams; } | { pathname: `/router/Router`; params?: Router.UnknownOutputParams; } | { pathname: `/types/common/data.types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/CreateEditProduct${`?${string}` | `#${string}` | ''}` | `/HomePage${`?${string}` | `#${string}` | ''}` | `/MainPage${`?${string}` | `#${string}` | ''}` | `/ProductAdd${`?${string}` | `#${string}` | ''}` | `/ProductPage${`?${string}` | `#${string}` | ''}` | `/ShopHeader${`?${string}` | `#${string}` | ''}` | `/ShopPage${`?${string}` | `#${string}` | ''}` | `/ShopProducts${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/api${`?${string}` | `#${string}` | ''}` | `/api/controllers/new-controller${`?${string}` | `#${string}` | ''}` | `/router/Router${`?${string}` | `#${string}` | ''}` | `/types/common/data.types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CreateEditProduct`; params?: Router.UnknownInputParams; } | { pathname: `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/MainPage`; params?: Router.UnknownInputParams; } | { pathname: `/ProductAdd`; params?: Router.UnknownInputParams; } | { pathname: `/ProductPage`; params?: Router.UnknownInputParams; } | { pathname: `/ShopHeader`; params?: Router.UnknownInputParams; } | { pathname: `/ShopPage`; params?: Router.UnknownInputParams; } | { pathname: `/ShopProducts`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/api`; params?: Router.UnknownInputParams; } | { pathname: `/api/controllers/new-controller`; params?: Router.UnknownInputParams; } | { pathname: `/router/Router`; params?: Router.UnknownInputParams; } | { pathname: `/types/common/data.types`; params?: Router.UnknownInputParams; };
    }
  }
}
