/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/src/RouterPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/api`; params?: Router.UnknownInputParams; } | { pathname: `/src/api/controllers/new-controller`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ShopHeader`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ShopProducts`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/change-data-backend/CreateEditProduct`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/MainPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/ProductAdd`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/ProductPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/ShopPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/common/data.types`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/src/App`; params?: Router.UnknownOutputParams; } | { pathname: `/src/RouterPage`; params?: Router.UnknownOutputParams; } | { pathname: `/src/api`; params?: Router.UnknownOutputParams; } | { pathname: `/src/api/controllers/new-controller`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/ShopHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/ShopProducts`; params?: Router.UnknownOutputParams; } | { pathname: `/src/components/change-data-backend/CreateEditProduct`; params?: Router.UnknownOutputParams; } | { pathname: `/src/pages/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/src/pages/MainPage`; params?: Router.UnknownOutputParams; } | { pathname: `/src/pages/ProductAdd`; params?: Router.UnknownOutputParams; } | { pathname: `/src/pages/ProductPage`; params?: Router.UnknownOutputParams; } | { pathname: `/src/pages/ShopPage`; params?: Router.UnknownOutputParams; } | { pathname: `/src/types/common/data.types`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/src/App${`?${string}` | `#${string}` | ''}` | `/src/RouterPage${`?${string}` | `#${string}` | ''}` | `/src/api${`?${string}` | `#${string}` | ''}` | `/src/api/controllers/new-controller${`?${string}` | `#${string}` | ''}` | `/src/components/ShopHeader${`?${string}` | `#${string}` | ''}` | `/src/components/ShopProducts${`?${string}` | `#${string}` | ''}` | `/src/components/change-data-backend/CreateEditProduct${`?${string}` | `#${string}` | ''}` | `/src/pages/HomePage${`?${string}` | `#${string}` | ''}` | `/src/pages/MainPage${`?${string}` | `#${string}` | ''}` | `/src/pages/ProductAdd${`?${string}` | `#${string}` | ''}` | `/src/pages/ProductPage${`?${string}` | `#${string}` | ''}` | `/src/pages/ShopPage${`?${string}` | `#${string}` | ''}` | `/src/types/common/data.types${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/src/RouterPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/api`; params?: Router.UnknownInputParams; } | { pathname: `/src/api/controllers/new-controller`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ShopHeader`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/ShopProducts`; params?: Router.UnknownInputParams; } | { pathname: `/src/components/change-data-backend/CreateEditProduct`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/MainPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/ProductAdd`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/ProductPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/pages/ShopPage`; params?: Router.UnknownInputParams; } | { pathname: `/src/types/common/data.types`; params?: Router.UnknownInputParams; };
    }
  }
}
